# -*- coding: utf-8 -*-
"""helloworld_github.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ci9cPchPnOpZQum6p39lEF6m4nHd4eVK
"""

print("Hello World!")